services:
  responsible-service:
    image: responsible-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db-responsible:
        condition: service_healthy
    environment:
      TZ: America/Sao_Paulo
      SPRING.APPLICATION.NAME: responsible-service
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3308/responsible_service?useSSL=false&use&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123

  db-responsible:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d responsible -p 5431" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: responsible_service
      POSTGRES_PORT: 5431
    command: postgres -p 5431
    ports:
      - "5431:5431"
networks:
  erudio-network:
    driver: bridge